-- Creación de la base de datos (Opcional)
-- CREATE DATABASE sistema_ventas;

---
--- 1. TABLA: ROLES
---
CREATE TABLE ROLES (
    id_rol SERIAL,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255),
    CONSTRAINT PK_ROLES PRIMARY KEY (id_rol)
);

---
--- 2. TABLA: CATEGORIAS
---
CREATE TABLE CATEGORIAS (
    id_categoria SERIAL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY (id_categoria)
);

---
--- 3. TABLA: USUARIOS
---
CREATE TABLE USUARIOS (
    id_usuario SERIAL,
    id_rol INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (id_usuario),
    CONSTRAINT FK_USUARIOS_ROLES FOREIGN KEY (id_rol) REFERENCES ROLES(id_rol)
);

---
--- 4. TABLA: PRODUCTOS
---
CREATE TABLE PRODUCTOS (
    id_producto SERIAL,
    id_categoria INT NOT NULL,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    precio_compra NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    precio_venta NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    stock_actual INT NOT NULL DEFAULT 0,
    stock_minimo INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (id_producto),
    CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (id_categoria) REFERENCES CATEGORIAS(id_categoria)
);

---
--- 5. TABLA: MOVIMIENTOS_INVENTARIO
---
CREATE TABLE MOVIMIENTOS_INVENTARIO (
    id_movimiento SERIAL,
    id_producto INT NOT NULL,
    id_usuario INT NOT NULL,
    tipo_movimiento VARCHAR(20) NOT NULL, -- Ej: 'ENTRADA', 'SALIDA'
    cantidad INT NOT NULL,
    stock_anterior INT NOT NULL,
    stock_nuevo INT NOT NULL,
    fecha_movimiento TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Añadido para control de tiempo
    CONSTRAINT PK_MOVIMIENTOS_INVENTARIO PRIMARY KEY (id_movimiento),
    CONSTRAINT FK_MOVIMIENTOS_PRODUCTOS FOREIGN KEY (id_producto) REFERENCES PRODUCTOS(id_producto),
    CONSTRAINT FK_MOVIMIENTOS_USUARIOS FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
);

---
--- 6. TABLA: VENTAS
---
CREATE TABLE VENTAS (
    id_venta SERIAL,
    id_usuario INT NOT NULL,
    folio VARCHAR(50) NOT NULL UNIQUE,
    subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    estado VARCHAR(20) NOT NULL DEFAULT 'COMPLETADA', -- Ej: 'PAGADA', 'CANCELADA'
    fecha_venta TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Añadido por buena práctica
    CONSTRAINT PK_VENTAS PRIMARY KEY (id_venta),
    CONSTRAINT FK_VENTAS_USUARIOS FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
);

---
--- 7. TABLA: DETALLE_VENTAS
---
CREATE TABLE DETALLE_VENTAS (
    id_detalle SERIAL,
    id_venta INT NOT NULL,
    id_producto INT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    CONSTRAINT PK_DETALLE_VENTAS PRIMARY KEY (id_detalle),
    CONSTRAINT FK_DETALLE_VENTAS_VENTAS FOREIGN KEY (id_venta) REFERENCES VENTAS(id_venta) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_VENTAS_PRODUCTOS FOREIGN KEY (id_producto) REFERENCES PRODUCTOS(id_producto)
);